# Spring DataSource Configuration
spring.datasource.url=jdbc:mysql://gostech.mysql.database.azure.com/swiftport-db?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=dev
spring.datasource.password=${LCPASSWORD}
